### ISSUE TITLE
头条滑条验证改算法了吗？

### ISSUE THREAD

**Issue by losesky** [senlizishi/sv-cracker#4]
部署以后系统模拟滑条到达正确位置松开后，显示验证失败，手动拖动滑条又能正常进入，这是什么原因啊？
![1682136515074](https://user-images.githubusercontent.com/904393/233761560-da58212c-26b9-4e6f-b847-c45bc1797531.png)

**Comment by senlizishi** [comment]
头条最近升级了反爬机制了，同时增加了手机短信验证 :sweat_smile:

**Comment by senlizishi** [comment]
这是轨迹被检测为非人工操作导致的，你可以试试换成 PID 算法生成轨迹 + 模拟抖动， PID 参数需要你自行试错法调整到最优值
